name: Welcome
# This is a demo workflow to show relationships between workflows

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SHARED_SECRET }} | rev
